---
# TFSec configuration for ECR Public module
severity: MEDIUM
minimum_severity: MEDIUM

# Include/exclude patterns
include_patterns:
  - "**/*.tf"
  - "**/*.tfvars"

exclude_patterns:
  - ".terraform/**"
  - "test/**"
  - "**/node_modules/**"

# Note: Custom checks require implementing Go code and compiling into TFSec
# ECR Public specific validation is handled by pre-commit hooks instead

# Exclude checks not relevant to ECR Public
exclude_checks:
  - aws-s3-enable-bucket-logging
  - aws-s3-enable-bucket-encryption  
  - aws-s3-enable-versioning
  - aws-s3-block-public-acls
  - aws-s3-block-public-policy
  - aws-s3-ignore-public-acls
  - aws-s3-no-public-buckets
  - aws-ecr-repository-customer-key-encryption  # ECR Public uses different encryption model
  - aws-ecr-enable-image-scans  # ECR Public has different scanning configuration
  - aws-ecr-repository-has-image-tag-immutability  # Different from ECR Public

# Include relevant checks
include_checks:
  - aws-iam-no-policy-wildcards
  - aws-general-secrets-sensitive-in-variable
  - aws-general-secrets-sensitive-in-local
  - terraform-required-version
  - terraform-required-providers

# Exclude directories
exclude_paths:
  - ".git/**"
  - ".terraform/**"
  - "test/**/*.tf"  # Test files may have different patterns
  - "examples/**/provider.tf"  # Examples may have different provider configs