name: ECR Public Feature Discovery

on:
  schedule:
    # Run weekly on Sundays at 00:00 UTC
    - cron: '0 0 * * 0'

  workflow_dispatch:
    inputs:
      provider_version:
        description: 'AWS Provider version to check (default: latest)'
        required: false
        default: 'latest'
        type: string
      dry_run:
        description: 'Run analysis without creating issues'
        required: false
        default: false
        type: boolean
      force_scan:
        description: 'Force full scan even if no changes detected'
        required: false
        default: false
        type: boolean

jobs:
  discover-ecrpublic-features:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write
      issues: write
      pull-requests: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Create feature tracker directory
        run: |
          mkdir -p .github/feature-tracker

          # Create initial tracker file if it doesn't exist
          if [ ! -f .github/feature-tracker/ecrpublic-features.json ]; then
            cat > .github/feature-tracker/ecrpublic-features.json << 'EOF'
          {
            "last_scan": "1970-01-01T00:00:00Z",
            "provider_version": "0.0.0",
            "scan_history": [],
            "features": {},
            "issues_created": []
          }
          EOF
            echo "Created initial feature tracker file"
          fi

      - name: Run Claude Code Feature Discovery
        id: claude-discovery
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

          # MCP Configuration for Terraform and Context7 documentation access
          mcp_config: |
            {
              "mcpServers": {
                "terraform": {
                  "command": "npx",
                  "args": [
                    "-y",
                    "@modelcontextprotocol/server-terraform@latest"
                  ]
                },
                "context7": {
                  "command": "npx",
                  "args": [
                    "-y",
                    "@upstash/context7-mcp@latest"
                  ]
                }
              }
            }

          # Allow necessary tools for feature discovery
          allowed_tools: |
            mcp__terraform-server__getProviderDocs
            mcp__terraform-server__resolveProviderDocID
            mcp__terraform-server__searchModules
            mcp__terraform-server__moduleDetails
            mcp__context7__resolve-library-id
            mcp__context7__get-library-docs
            Bash(git diff)
            Bash(git status)
            Bash(gh issue create)
            Bash(gh issue list)
            Bash(jq)
            Bash(cat)
            Bash(echo)

          # Direct prompt for Claude Code to perform feature discovery
          direct_prompt: |
            # ECR Public Feature Discovery Analysis

            You are performing automated feature discovery for the terraform-aws-ecrpublic module.

            ## Objective
            Analyze the latest AWS provider ECR Public resources and compare them with the current module implementation to identify:
            1. **New Features**: ECR Public resources/arguments not yet implemented
            2. **Deprecations**: Features marked as deprecated in the provider
            3. **Bug Fixes**: Important fixes mentioned in provider changelogs

            ## Configuration
            - Provider Version: ${{ inputs.provider_version || 'latest' }}
            - Dry Run Mode: ${{ inputs.dry_run }}
            - Force Scan: ${{ inputs.force_scan }}

            ## Process

            ### Step 1: Load Current State
            Read the feature tracking database:
            ```bash
            cat .github/feature-tracker/ecrpublic-features.json
            ```

            ### Step 2: Fetch AWS Provider ECR Public Documentation
            Use the Terraform MCP server to get the latest ECR Public documentation:

            1. Use `mcp__terraform-server__resolveProviderDocID` with:
               - providerName: "aws"
               - providerNamespace: "hashicorp"
               - serviceSlug: "ecrpublic"
               - providerVersion: "${{ inputs.provider_version || 'latest' }}"
               - providerDataType: "resources"

            2. Get documentation for all ECR Public resources (aws_ecrpublic_*)
            3. Also check data sources with providerDataType: "data-sources"

            ### Step 3: Analyze Current Module Implementation
            Examine these files to understand current implementation:
            - `main.tf` - Primary ECR Public repository resource
            - `variables.tf` - Input variables and catalog data configuration
            - `outputs.tf` - Module outputs
            - `examples/` directory structure:
              - `using_objects/` - Object-based catalog data configuration
              - `using_variables/` - Variable-based catalog data configuration

            Create an inventory of:
            - Implemented resources (aws_ecrpublic_repository)
            - Implemented arguments/attributes (catalog_data, timeouts, etc.)
            - Configuration patterns used in examples

            ### Step 4: Comparison and Analysis
            Compare provider documentation with module implementation:

            **New Features to Look For:**
            - New `aws_ecrpublic_*` resources not in the module
            - New arguments on existing resources (repository, catalog data, etc.)
            - New data sources (`data.aws_ecrpublic_*`)
            - New catalog data fields for ECR Public Gallery
            - New repository configuration options
            - New timeout and lifecycle management features
            - New authentication and authorization features
            - New registry scanning and security capabilities

            **Deprecations to Check:**
            - Arguments marked as deprecated
            - Resources marked for removal
            - Catalog data patterns no longer recommended
            - Configuration approaches that are outdated

            **Bug Fixes:**
            - Check Context7 for AWS provider changelogs
            - Look for ECR Public-related fixes that might affect the module

            ### Step 5: Issue Creation
            For each significant finding:

            **If NOT in dry run mode (${{ inputs.dry_run }} == false):**

            Create GitHub issues using templates:

            ```bash
            # For new features
            gh issue create --template .github/ISSUE_TEMPLATE/new-ecrpublic-feature.md \
              --title "feat: Add support for [feature_name]" \
              --label "enhancement,aws-provider-update,auto-discovered" \
              --assignee "@me"

            # For deprecations
            gh issue create --template .github/ISSUE_TEMPLATE/ecrpublic-deprecation.md \
              --title "chore: Handle deprecation of [feature_name]" \
              --label "deprecation,breaking-change,auto-discovered" \
              --assignee "@me"

            # For bug fixes
            gh issue create --template .github/ISSUE_TEMPLATE/ecrpublic-bug-fix.md \
              --title "fix: Address [bug_description]" \
              --label "bug,aws-provider-update,auto-discovered" \
              --assignee "@me"
            ```

            ### Step 6: Update Feature Tracker
            Update `.github/feature-tracker/ecrpublic-features.json` with:
            - Current scan timestamp
            - Provider version analyzed
            - New findings
            - Issues created
            - Scan summary

            ### Step 7: Generate Summary Report
            Create a comprehensive summary including:
            - Features discovered: count and details
            - Deprecations found: count and impact
            - Issues created: numbers and links
            - Recommendations for next steps

            ## Important Notes
            - Skip creating issues for features already tracked as "implemented"
            - Check existing GitHub issues to avoid duplicates
            - Prioritize ECR Public Gallery and repository management changes
            - Focus on ECR Public-specific features (ignore general ECR private features)
            - Pay special attention to catalog data, public gallery, and repository configurations
            - Consider us-east-1 region constraints specific to ECR Public
            - Look for improvements to public repository visibility and discoverability

            ## Expected Output
            Provide a detailed report of your analysis and actions taken.

      - name: Commit feature tracker updates
        if: steps.claude-discovery.conclusion == 'success'
        run: |
          set -euo pipefail

          # Check if there are changes to commit
          if git diff --quiet .github/feature-tracker/; then
            echo "No changes to feature tracker detected"
            exit 0
          fi

          # Configure git
          git config --global user.name "ECR Public Feature Discovery Bot"
          git config --global user.email "actions@github.com"

          # Commit changes
          git add .github/feature-tracker/
          git commit -m "chore: update ECR Public feature discovery tracker

          - Updated feature tracking database
          - Scan completed: $(date -u '+%Y-%m-%d %H:%M:%S UTC')
          - Provider version: ${{ inputs.provider_version || 'latest' }}

          [skip ci]"

          # Push changes
          git push origin HEAD

          echo "Feature tracker updated successfully"

      - name: Workflow Summary
        if: always()
        run: |
          echo "## 🔍 ECR Public Feature Discovery Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          # Configuration
          echo "### ⚙️ Configuration" >> $GITHUB_STEP_SUMMARY
          echo "- **Provider Version**: \`${{ inputs.provider_version || 'latest' }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **Dry Run Mode**: \`${{ inputs.dry_run }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **Force Scan**: \`${{ inputs.force_scan }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **Triggered**: \`${{ github.event_name }}\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          # MCP Configuration
          echo "### 🔗 MCP Servers" >> $GITHUB_STEP_SUMMARY
          echo "- **Terraform MCP**: \`@modelcontextprotocol/server-terraform@latest\`" >> $GITHUB_STEP_SUMMARY
          echo "- **Context7 MCP**: \`@upstash/context7-mcp@latest\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          # Status
          echo "### 📊 Execution Status" >> $GITHUB_STEP_SUMMARY
          if [ "${{ steps.claude-discovery.conclusion }}" = "success" ]; then
            echo "- ✅ **Feature Discovery**: Completed successfully" >> $GITHUB_STEP_SUMMARY
          else
            echo "- ❌ **Feature Discovery**: Failed" >> $GITHUB_STEP_SUMMARY
          fi
          echo "" >> $GITHUB_STEP_SUMMARY

          # Available Commands
          echo "### 🚀 Manual Execution" >> $GITHUB_STEP_SUMMARY
          echo "Run feature discovery manually:" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
          echo "# Standard discovery" >> $GITHUB_STEP_SUMMARY
          echo "gh workflow run feature-discovery.yml" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "# Dry run mode" >> $GITHUB_STEP_SUMMARY
          echo "gh workflow run feature-discovery.yml -f dry_run=true" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "# Specific provider version" >> $GITHUB_STEP_SUMMARY
          echo "gh workflow run feature-discovery.yml -f provider_version=5.82.0" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
